/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RiwayatRouteImport } from './routes/riwayat'
import { Route as SimulasiRouteImport } from './routes/simulasi'
import { Route as UjianRouteImport } from './routes/ujian'
import { Route as HasilIdRouteImport } from './routes/hasil.$id'
import { Route as ReviewIdRouteImport } from './routes/review.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulasiRoute = SimulasiRouteImport.update({
  id: '/simulasi',
  path: '/simulasi',
  getParentRoute: () => rootRouteImport,
} as any)
const UjianRoute = UjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilIdRoute = HasilIdRouteImport.update({
  id: '/hasil/$id',
  path: '/hasil/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIdRoute = ReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profil': typeof ProfilRoute
  '/riwayat': typeof RiwayatRoute
  '/simulasi': typeof SimulasiRoute
  '/ujian': typeof UjianRoute
  '/hasil/$id': typeof HasilIdRoute
  '/review/$id': typeof ReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profil': typeof ProfilRoute
  '/riwayat': typeof RiwayatRoute
  '/simulasi': typeof SimulasiRoute
  '/ujian': typeof UjianRoute
  '/hasil/$id': typeof HasilIdRoute
  '/review/$id': typeof ReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profil': typeof ProfilRoute
  '/riwayat': typeof RiwayatRoute
  '/simulasi': typeof SimulasiRoute
  '/ujian': typeof UjianRoute
  '/hasil/$id': typeof HasilIdRoute
  '/review/$id': typeof ReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/profil'
    | '/riwayat'
    | '/simulasi'
    | '/ujian'
    | '/hasil/$id'
    | '/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/profil'
    | '/riwayat'
    | '/simulasi'
    | '/ujian'
    | '/hasil/$id'
    | '/review/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/profil'
    | '/riwayat'
    | '/simulasi'
    | '/ujian'
    | '/hasil/$id'
    | '/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfilRoute: typeof ProfilRoute
  RiwayatRoute: typeof RiwayatRoute
  SimulasiRoute: typeof SimulasiRoute
  UjianRoute: typeof UjianRoute
  HasilIdRoute: typeof HasilIdRoute
  ReviewIdRoute: typeof ReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulasi': {
      id: '/simulasi'
      path: '/simulasi'
      fullPath: '/simulasi'
      preLoaderRoute: typeof SimulasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ujian': {
      id: '/ujian'
      path: '/ujian'
      fullPath: '/ujian'
      preLoaderRoute: typeof UjianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil/$id': {
      id: '/hasil/$id'
      path: '/hasil/$id'
      fullPath: '/hasil/$id'
      preLoaderRoute: typeof HasilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$id': {
      id: '/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof ReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfilRoute: ProfilRoute,
  RiwayatRoute: RiwayatRoute,
  SimulasiRoute: SimulasiRoute,
  UjianRoute: UjianRoute,
  HasilIdRoute: HasilIdRoute,
  ReviewIdRoute: ReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
